services:
  # start the db image and map to port 27017
  db:
    build: ./db
    restart: always
    ports: [27017:27017]

  web:
    # start up the web app image and map to localhost
    image: salemsparta/eng89_multi-stage
    restart: always
    ports: [80:3000]
    # set variable for db port
    environment:
      - DB_HOST=mongodb://db:27017/posts
    # links the two images 
    depends_on:
      - db